__title__ = 'anatqc'
__description__ = 'Anatomical QC'
__url__ = 'https://github.com/harvard-nrg/anatqc'
__version__ = '0.3.5'
__author__ = 'Neuroinformatics Research Group'
__author_email__ = 'info@neuroinfo.org'
